import type { Category, Task } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-daily',
    name: 'Daily Tasks',
    icon: 'Sparkles',
    accent: '#8b5cf6',
    position: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-academics',
    name: 'Academics',
    icon: 'GraduationCap',
    accent: '#3b82f6',
    position: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-work',
    name: 'Other Work',
    icon: 'Briefcase',
    accent: '#10b981',
    position: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-instagram',
    name: 'Instagram',
    icon: 'Camera',
    accent: '#f43f5e',
    position: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat-linkedin',
    name: 'LinkedIn',
    icon: 'Share2',
    accent: '#06b6d4',
    position: 4,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-rec-1',
    title: 'Accounts / Corporate Law',
    notes: '30 mins revision on module 4 case studies',
    categoryId: 'cat-academics',
    priority: 'high',
    isRecurring: true,
    recurrenceRule: {
      id: 'rec-1',
      taskId: 'task-rec-1',
      frequency: 'daily',
      active: true,
      startDate: new Date().toISOString().split('T')[0],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-rec-2',
    title: 'Exercise / Workout',
    notes: 'Morning cardio & strength training session',
    categoryId: 'cat-daily',
    priority: 'high',
    isRecurring: true,
    recurrenceRule: {
      id: 'rec-2',
      taskId: 'task-rec-2',
      frequency: 'daily',
      active: true,
      startDate: new Date().toISOString().split('T')[0],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-rec-3',
    title: 'Meditation',
    notes: '15 mins mindfulness & breathing exercises',
    categoryId: 'cat-daily',
    priority: 'medium',
    isRecurring: true,
    recurrenceRule: {
      id: 'rec-3',
      taskId: 'task-rec-3',
      frequency: 'daily',
      active: true,
      startDate: new Date().toISOString().split('T')[0],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-1',
    title: 'Cloud Computing Assignment',
    notes: 'Complete chapter 5 exercises and lab report',
    categoryId: 'cat-academics',
    priority: 'high',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-2',
    title: 'Deep Learning Module',
    notes: 'Review neural network architectures and assignments',
    categoryId: 'cat-academics',
    priority: 'medium',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-3',
    title: 'Website Updates',
    notes: 'Refresh portfolio and update project descriptions',
    categoryId: 'cat-work',
    priority: 'medium',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-4',
    title: 'Power BI + Excel Dashboard',
    notes: 'Build analytics dashboard for internship project',
    categoryId: 'cat-work',
    priority: 'high',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-5',
    title: 'Instagram — Alumni Meet Content',
    notes: 'Plan and draft content for upcoming alumni meet post',
    categoryId: 'cat-instagram',
    priority: 'medium',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task-backlog-6',
    title: 'LinkedIn — Internship Post',
    notes: 'Write post about current internship experience and learnings',
    categoryId: 'cat-linkedin',
    priority: 'medium',
    isRecurring: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export function formatDateKey(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}
